export const QUERY_KEYS = {
  WORDS: "WORDS",
  FORWARD_ASSOCIATION: "FORWARD_ASSOCIATION",
  BACKWARD_ASSOCIATION: "BACKWARD_ASSOCIATION",
  RANDOM_FORWARD_ASSOCIATION: "RANDOM_FORWARD_ASSOCIATION",
  RANDOM_BACKWARD_ASSOCIATION: "RANDOM_BACKWARD_ASSOCIATION",
};
